update=2018/09/29 0:36:50
last_client=kicad
[eeschema]
version=1
LibDir=../../MyLibrary/component
[eeschema/libraries]
LibName1=SPRESENSE_ESP8266_v02-cache
LibName2=C:/Program Files/KiCad/share/kicad/library/74xgxx
LibName3=C:/Program Files/KiCad/share/kicad/library/74xx
LibName4=C:/Program Files/KiCad/share/kicad/library/ac-dc
LibName5=C:/Program Files/KiCad/share/kicad/library/actel
LibName6=C:/Program Files/KiCad/share/kicad/library/adc-dac
LibName7=C:/Program Files/KiCad/share/kicad/library/allegro
LibName8=C:/Program Files/KiCad/share/kicad/library/Altera
LibName9=C:/Program Files/KiCad/share/kicad/library/analog_devices
LibName10=C:/Program Files/KiCad/share/kicad/library/analog_switches
LibName11=C:/Program Files/KiCad/share/kicad/library/atmel
LibName12=C:/Program Files/KiCad/share/kicad/library/audio
LibName13=C:/Program Files/KiCad/share/kicad/library/battery_management
LibName14=C:/Program Files/KiCad/share/kicad/library/bbd
LibName15=C:/Program Files/KiCad/share/kicad/library/bosch
LibName16=C:/Program Files/KiCad/share/kicad/library/brooktre
LibName17=C:/Program Files/KiCad/share/kicad/library/cmos_ieee
LibName18=C:/Program Files/KiCad/share/kicad/library/cmos4000
LibName19=C:/Program Files/KiCad/share/kicad/library/conn
LibName20=C:/Program Files/KiCad/share/kicad/library/contrib
LibName21=C:/Program Files/KiCad/share/kicad/library/cypress
LibName22=C:/Program Files/KiCad/share/kicad/library/dc-dc
LibName23=C:/Program Files/KiCad/share/kicad/library/device
LibName24=C:/Program Files/KiCad/share/kicad/library/digital-audio
LibName25=C:/Program Files/KiCad/share/kicad/library/diode
LibName26=C:/Program Files/KiCad/share/kicad/library/display
LibName27=C:/Program Files/KiCad/share/kicad/library/dsp
LibName28=C:/Program Files/KiCad/share/kicad/library/elec-unifil
LibName29=C:/Program Files/KiCad/share/kicad/library/ESD_Protection
LibName30=C:/Program Files/KiCad/share/kicad/library/ftdi
LibName31=C:/Program Files/KiCad/share/kicad/library/gennum
LibName32=C:/Program Files/KiCad/share/kicad/library/graphic
LibName33=C:/Program Files/KiCad/share/kicad/library/graphic_symbols
LibName34=C:/Program Files/KiCad/share/kicad/library/hc11
LibName35=C:/Program Files/KiCad/share/kicad/library/infineon
LibName36=C:/Program Files/KiCad/share/kicad/library/intel
LibName37=C:/Program Files/KiCad/share/kicad/library/interface
LibName38=C:/Program Files/KiCad/share/kicad/library/intersil
LibName39=C:/Program Files/KiCad/share/kicad/library/ir
LibName40=C:/Program Files/KiCad/share/kicad/library/Lattice
LibName41=C:/Program Files/KiCad/share/kicad/library/leds
LibName42=C:/Program Files/KiCad/share/kicad/library/LEM
LibName43=C:/Program Files/KiCad/share/kicad/library/linear
LibName44=C:/Program Files/KiCad/share/kicad/library/logic_programmable
LibName45=C:/Program Files/KiCad/share/kicad/library/logo
LibName46=C:/Program Files/KiCad/share/kicad/library/maxim
LibName47=C:/Program Files/KiCad/share/kicad/library/mechanical
LibName48=C:/Program Files/KiCad/share/kicad/library/memory
LibName49=C:/Program Files/KiCad/share/kicad/library/microchip
LibName50=C:/Program Files/KiCad/share/kicad/library/microchip_dspic33dsc
LibName51=C:/Program Files/KiCad/share/kicad/library/microchip_pic10mcu
LibName52=C:/Program Files/KiCad/share/kicad/library/microchip_pic12mcu
LibName53=C:/Program Files/KiCad/share/kicad/library/microchip_pic16mcu
LibName54=C:/Program Files/KiCad/share/kicad/library/microchip_pic18mcu
LibName55=C:/Program Files/KiCad/share/kicad/library/microchip_pic24mcu
LibName56=C:/Program Files/KiCad/share/kicad/library/microchip_pic32mcu
LibName57=C:/Program Files/KiCad/share/kicad/library/microcontrollers
LibName58=C:/Program Files/KiCad/share/kicad/library/modules
LibName59=C:/Program Files/KiCad/share/kicad/library/motor_drivers
LibName60=C:/Program Files/KiCad/share/kicad/library/motorola
LibName61=C:/Program Files/KiCad/share/kicad/library/motors
LibName62=C:/Program Files/KiCad/share/kicad/library/msp430
LibName63=C:/Program Files/KiCad/share/kicad/library/nordicsemi
LibName64=C:/Program Files/KiCad/share/kicad/library/nxp
LibName65=C:/Program Files/KiCad/share/kicad/library/nxp_armmcu
LibName66=C:/Program Files/KiCad/share/kicad/library/onsemi
LibName67=C:/Program Files/KiCad/share/kicad/library/opto
LibName68=C:/Program Files/KiCad/share/kicad/library/Oscillators
LibName69=C:/Program Files/KiCad/share/kicad/library/philips
LibName70=C:/Program Files/KiCad/share/kicad/library/power
LibName71=C:/Program Files/KiCad/share/kicad/library/Power_Management
LibName72=C:/Program Files/KiCad/share/kicad/library/powerint
LibName73=C:/Program Files/KiCad/share/kicad/library/pspice
LibName74=C:/Program Files/KiCad/share/kicad/library/references
LibName75=C:/Program Files/KiCad/share/kicad/library/regul
LibName76=C:/Program Files/KiCad/share/kicad/library/relays
LibName77=C:/Program Files/KiCad/share/kicad/library/rfcom
LibName78=C:/Program Files/KiCad/share/kicad/library/RFSolutions
LibName79=C:/Program Files/KiCad/share/kicad/library/sensors
LibName80=C:/Program Files/KiCad/share/kicad/library/silabs
LibName81=C:/Program Files/KiCad/share/kicad/library/siliconi
LibName82=C:/Program Files/KiCad/share/kicad/library/stm8
LibName83=C:/Program Files/KiCad/share/kicad/library/stm32
LibName84=C:/Program Files/KiCad/share/kicad/library/supertex
LibName85=C:/Program Files/KiCad/share/kicad/library/switches
LibName86=C:/Program Files/KiCad/share/kicad/library/texas
LibName87=C:/Program Files/KiCad/share/kicad/library/transf
LibName88=C:/Program Files/KiCad/share/kicad/library/transistors
LibName89=C:/Program Files/KiCad/share/kicad/library/triac_thyristor
LibName90=C:/Program Files/KiCad/share/kicad/library/ttl_ieee
LibName91=C:/Program Files/KiCad/share/kicad/library/valves
LibName92=C:/Program Files/KiCad/share/kicad/library/video
LibName93=C:/Program Files/KiCad/share/kicad/library/wiznet
LibName94=C:/Program Files/KiCad/share/kicad/library/Worldsemi
LibName95=C:/Program Files/KiCad/share/kicad/library/Xicor
LibName96=C:/Program Files/KiCad/share/kicad/library/xilinx
LibName97=C:/Program Files/KiCad/share/kicad/library/zetex
LibName98=C:/Program Files/KiCad/share/kicad/library/Zilog
LibName99=D:/MyDocuments/kicad/MyLibrary/component/941H-2C-5D
LibName100=D:/MyDocuments/kicad/MyLibrary/component/ADP3338AKCZ­3.3-RL
LibName101=D:/MyDocuments/kicad/MyLibrary/component/Bluetooth
LibName102=D:/MyDocuments/kicad/MyLibrary/component/BP5293
LibName103=D:/MyDocuments/kicad/MyLibrary/component/bss138
LibName104=D:/MyDocuments/kicad/MyLibrary/component/CH340T
LibName105=D:/MyDocuments/kicad/MyLibrary/component/con_phoenix_SPTAF1
LibName106=D:/MyDocuments/kicad/MyLibrary/component/connector
LibName107=D:/MyDocuments/kicad/MyLibrary/component/cp210_mlp28
LibName108=D:/MyDocuments/kicad/MyLibrary/component/CRD
LibName109=D:/MyDocuments/kicad/MyLibrary/component/DM3AT-SF-PEJM5
LibName110=D:/MyDocuments/kicad/MyLibrary/component/esp32
LibName111=D:/MyDocuments/kicad/MyLibrary/component/ESP8266
LibName112=D:/MyDocuments/kicad/MyLibrary/component/HT9172
LibName113=D:/MyDocuments/kicad/MyLibrary/component/IRrcv
LibName114=D:/MyDocuments/kicad/MyLibrary/component/ka2411
LibName115=D:/MyDocuments/kicad/MyLibrary/component/L293D
LibName116=D:/MyDocuments/kicad/MyLibrary/component/logo
LibName117=D:/MyDocuments/kicad/MyLibrary/component/LSM6DS3
LibName118=D:/MyDocuments/kicad/MyLibrary/component/LSM303D
LibName119=D:/MyDocuments/kicad/MyLibrary/component/OSH_logo
LibName120=D:/MyDocuments/kicad/MyLibrary/component/PCA9685
LibName121=D:/MyDocuments/kicad/MyLibrary/component/rj11_7002-6p6c-x
LibName122=D:/MyDocuments/kicad/MyLibrary/component/sliede_sw_01
LibName123=D:/MyDocuments/kicad/MyLibrary/component/solderjumper
LibName124=D:/MyDocuments/kicad/MyLibrary/component/sp0503bahtg_sot143-4n
LibName125=D:/MyDocuments/kicad/MyLibrary/component/tact_sw
LibName126=D:/MyDocuments/kicad/MyLibrary/component/usb-serial
LibName127=D:/MyDocuments/kicad/MyLibrary/component/Y14H-1C-5DS
LibName128=WS2812B
LibName129=osrb38c9aa
LibName130=mic5219-BM5
LibName131=mosfet-n-sot23_sot23
[schematic_editor]
version=1
PageLayoutDescrFile=
PlotDirectoryName=
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=Pcbnew
SpiceForceRefPrefix=0
SpiceUseNetNumbers=0
LabSize=60
